services:
  db:
    image: postgres:15-alpine
    container_name: hw4-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: trip_timeline_db
      POSTGRES_USER: trip_user
      POSTGRES_PASSWORD: trip_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U trip_user -d trip_timeline_db"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: hw4-backend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      PORT: 3000
      DATABASE_URL: postgresql://trip_user:trip_password@db:5432/trip_timeline_db
      JWT_ACCESS_SECRET: dev-access-secret-change-in-production
      JWT_REFRESH_SECRET: dev-refresh-secret-change-in-production
      JWT_ACCESS_EXPIRES_IN: 15m
      JWT_REFRESH_EXPIRES_IN: 7d
      GOOGLE_MAPS_API_KEY: ${GOOGLE_MAPS_API_KEY:-YOUR_API_KEY_HERE}
      FRONTEND_URL: http://localhost:5173
    depends_on:
      db:
        condition: service_healthy
        restart: true
    volumes:
      - ./backend/src:/app/src:cached
      - ./backend/prisma:/app/prisma:cached

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: hw4-frontend
    restart: unless-stopped
    ports:
      - "5173:5173"
    environment:
      VITE_API_URL: http://localhost:3000
      VITE_GOOGLE_MAPS_API_KEY: ${GOOGLE_MAPS_API_KEY:-YOUR_API_KEY_HERE}
    depends_on:
      backend:
        condition: service_started
    volumes:
      - ./frontend:/app:cached
      - frontend_node_modules:/app/node_modules
    stdin_open: true
    tty: true

volumes:
  postgres_data:
  backend_node_modules:
  frontend_node_modules:

networks:
  default:
    name: hw4_network

